### PR TITLE
always update setuptools before travis run

### LINKED ISSUE #656: Installation failures with setuptools 34 & 35
This is a continuation of tox-dev/tox-travis#76. 

Travis's python 3.4 environment ships a broken version of setuptools (more details in the tox-travis issue). When upgrading dependencies that setuptools itself depends on (such as six in this case) a race condition may occur where the package temporarily does not exist, causing the installation to fail.

### PR DESCRIPTION
**Pull request by gaborbernat**
resolves #656

### CODE REVIEW

**Comment by gaborbernat** [comment]
@cryvate technically this is a pip issue, :-) and the underlying issue is already with six (which is a dependency of setuptools), so here I've treated just the bad part :-)

**Comment by cryvate** [comment]
@gaborbernat thanks, I didn't realise that was happening, for others interested, see https://github.com/pypa/setuptools/issues/964

**Comment by rpkilby** [comment]
Hi @gaborbernat - I think you need to add the `-U` flag to the six install. If you look at the build output, it shows that the requirement is already satisfied ([output](https://travis-ci.org/tox-dev/tox/jobs/304005231#L452-L453)). It doesn't upgrade until the upgrade of tox.

**Comment by rpkilby** [comment]
As evidence of this, see this [build](https://travis-ci.org/tox-dev/tox/builds/304474808).

**Pull request merged**
