### PR TITLE
Consider complete envs, not factors

### PR DESCRIPTION
**Pull request by stephenfin**
To determine whether we have been given a valid *env*, we compare the *factors* of the *env* to our known set of *factors*. If a testenv contains a series of valid factors, we assume the testenv is valid. This is an incorrect assumption: a testenv is only valid if it defined in the configuration file *or* is one of the "special" auto-generated testenvs like e.g. 'py310'. Correct this mistake.

This is a draft PR while I wait for feedback on my general idea here. I'd like to confirm that my understanding of expected behavior is correct.

Signed-off-by: Stephen Finucane <stephen@that.guru>
Closes: #3219

- [ ] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [ ] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation

### CODE REVIEW

**Comment by stephenfin** [comment]
This is currently failing a few tests because it does not allow for autogenerated testenvs based on factors defined in e.g. `[testenv] commands`. For example:

```
[testenv]
commands =
    foo: echo "got foo"
    bar: echo "got bar"
```

That this worked suprised me: I'd normally have defined this in my `tox.ini` like so:

```
[testenv:py{310,311,312}{,-cov}]
```

but that is definitely duplication. I can work to fix this but again, I want to confirm that the bug I'm seeing is indeed a bug (it really feels like one)

**Comment by stephenfin** [comment]
Converting to non-draft, even though it's clearly not complete, so that folks see it.

**Comment by gaborbernat** [comment]
> Converting to non-draft, even though it's clearly not complete, so that folks see it.

We see, without it too, was waiting for you to pass the CI.

> This is an incorrect assumption: a testenv is only valid if it defined in the configuration file _or_ is one of the "special" auto-generated testenvs like e.g. 'py310'. Correct this mistake.

I'd say, in general, yes. But note, I want to allow `py313-magic` if `py312-magic` is defined. This will make testing a new Python interpreter version not require defining that in the configuration.

**Comment by gaborbernat** [comment]
Closing as seems it stalled, we can reopen if you get time again for it.

**Pull request closed without merging**
