### PR TITLE
Fix `commands_pre`/`commands_post` documentation.

### PR DESCRIPTION
**Pull request by benoit-pierre**
Mention the minimum version required.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Should be fixed.

**Comment by gaborbernat** [comment]
Thanks!

**Comment by cjerdonek** [comment]
Has there been any consideration of having tox issue a warning if unrecognized key values are encountered? That could help people to know they could need to upgrade. Currently, such key values (e.g. `commands_pre`) are silently skipped if the user doesn't have a new enough version.

**Comment by gaborbernat** [comment]
No, and probably we'll never have it. This would be backwards incompatible change. Note people can at the moment use empty keywords together with substitution to re-use fields, e.g.:

```
[testenv]
doc_python = python3

[testenv:doc_build]
basepython = {[testenv]doc_python}

[testenv:doc_build2]
basepython = {[testenv]doc_python}

``` 

If you depend on a feature that's only available under a given version you should specify it via the minversion https://tox.readthedocs.io/en/latest/config.html#conf-minversion

**Pull request merged**
