### PR TITLE
Added py36 to tox.ini

### PR DESCRIPTION
**Pull request by andriisoldatenko**
>Python 3.6.0 is the newest major release of the Python language, and it contains many new features and optimizations.
[Python 3.6.0](https://www.python.org/downloads/release/python-360/)

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks! 

Could you please also update `appveyor.yml` and `.travis.yml`? In `.travis.yml` I believe we can use the standard `'3.6'` Python instead of `- 3.6-dev` (untested).

**Comment by andriisoldatenko** [comment]
Yes sure.

**Comment by nicoddemus** [comment]
Update: it seems Travis still needs to use `3.6-dev` though.

**Comment by andriisoldatenko** [comment]
@nicoddemus I've already done this change in couple projects.
I think now we have `3.7-dev`.

**Pull request merged**
