### PR TITLE
Move time mocking from freezegun to time-machine

### PR DESCRIPTION
**Pull request by adamchainz**
It's faster :)

In this case, about 0.1 seconds are saved... there aren't that many tests using it.

# Thanks for contribution

Please, make sure you address all the checklists (for details on how see
[development documentation](http://tox.readthedocs.org/en/latest/development.html#development))!

- [x] ran the linter to address style issues (`tox -e fix_lint`)
- [x] wrote descriptive pull request text
- [x] ensured there are test(s) validating the fix
- **n/a** added news fragment in `docs/changelog` folder
- **n/a** updated/extended the documentation

### CODE REVIEW

**Comment by jugmac00** [comment]
Thanks, Adam!

@gaborbernat There was some discussion on Twitter, especially @pganssle had some concerns about time-machine.
https://twitter.com/AdamChainz/status/1513446705567571969

I think this needs a closer look, though a win of 0.1 s sounds pretty tempting :-)

**Comment by adamchainz** [comment]
I don't think those concerns affect the tests here, which I think are freezing time purely to guarantee that all operations are seen as taking `0.0s` for consistent output :)

**Review by gaborbernat — APPROVED** [review]

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Can you please a changelog for this otherwise looks alright

**Comment by adamchainz** [comment]
> Can you please a changelog for this otherwise looks alright

There aren't any other files in `docs/changelog` on the `rewrite` branch - are you sure?

Also I tend to avoid adding release notes for internal-only changes. Users don't need to read about how tox's own test suite has changed.

**Comment by jayaddison** [comment]
Related to this: there's some use of `time.monotonic` throughout the `tox` codebase, which [isn't supported by `time-machine`](https://github.com/adamchainz/time-machine/issues/29) -- I think it might explain some test flakiness recently (particularly on Windows 2022, for whatever reason)

**Review by gaborbernat — APPROVED** [review]

**Comment by hroncok** [comment]
We don't have time-machine packaged in Fedora, so we "simply" tried removing all the decorators and the tests passed. What is the purpose of this dependency?

**Comment by gaborbernat** [comment]
I think the spinner tests elapsed field here https://github.com/tox-dev/tox/blob/fd25b2b141383b1e3511c82b7429fbf04c1cb4d1/tests/util/test_spinner.py#L16 might change depending on how fast machine you're running

**Pull request merged**
