### PR TITLE
WIP - Add VSTS integration

### PR DESCRIPTION
**Pull request by gaborbernat**
Try out using VSTS.

### CODE REVIEW

**Comment by zooba** [comment]
@gaborbernat I'm writing you an email now, but you'll need to point VSTS at your fork to get it to use this file. It won't use a definition that's new in a PR (though I believe it will use a newer version in a PR if it was already there in the target branch)

**Comment by gaborbernat** [comment]
I just put the base into the master; and in this PR I just update it. It still does not work like that? :+1:

**Comment by zooba** [comment]
It looks like you may also need to reauthorize VSTS. The errors on the builds look like an auth issue...

**Comment by zooba** [comment]
For extra joy, you should add `--junitxml=test-results.xml` to your pytest command line and then add this snippet after running the tests:

```yaml
- task: PublishTestResults@2
  displayName: Publish Test Results **/test-results.xml
  inputs:
    testResultsFiles: '**/test-results.xml'
  condition: always()
```

This will upload test results to the TEST tab.

**Comment by gaborbernat** [comment]
Yeah gathered, for now I'm more worried about the PR hook working though :thinking: did the re-enable authentication still nothing.

**Comment by zooba** [comment]
Well, we got a successful build at least :)

You might need to add this to the YAML file (copied from the CPython repo, so adjust branches/paths as necessary - and I'm fairly sure we're still waiting for the paths parameter to be supported for GitHub, so it may not be working yet):

```yaml
trigger:
  branches:
    include:
    - master
    - 3.7
    - 3.6
  paths:
    exclude:
    - Doc/*
    - Tools/*
```

**Comment by zooba** [comment]
And it may also need to be merged before it gets picked up (since the main repo is going to provide the trigger settings).

**Comment by gaborbernat** [comment]
Ok, done :+1: still not triggering :thinking: the PR webhook returns with ``{"count":0,"value":[]}``

**Pull request merged**
