### PR TITLE
Normalize path separators for env vars changed by setenv command

### PR DESCRIPTION
**Pull request by rogalski**

### CODE REVIEW

**Comment by hpk42** [comment]
Thanks @rogalski for the PR.  It just occured to me that we could introduce a substitution ``{:}`` which would be substituted by ``os.pathsep``.  It could be used anywhere.  I like it because it is more direct  than the meta declaration "env_path_vars".  What do you and others think?  (your PR and especially the tests could be re-used so your effort on the PR is not lost).

**Comment by nicoddemus** [comment]
> It just occured to me that we could introduce a substitution {:} which would be substituted by os.pathsep. It could be used anywhere.

I like it, seems more straightforward.

**Comment by RonnyPfannschmidt** [comment]
scarry ^^

**Comment by rogalski** [comment]
@hpk42 there was a proposal in original issue to use `{os.pathsep}` as substitute : https://bitbucket.org/hpk42/tox/issues/344/consider-normalizing-path-separators-in

> export {os.pathsep} as possible substitute - explicit, easy, but results in kind of ugly looking tox.ini

But colon is much shorter, and I guess shorter is better in this case...
I'll implement `{:}` substitute. Then we can evaluate which approach looks nicer. 

Thanks for feedback, guys!

**Comment by hpk42** [comment]
thanks for providing the alternative, @rogalski

**Pull request closed without merging**
