### PR TITLE
toxworkdir: use realpath

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/tox-dev/tox/issues/1169.

### CODE REVIEW

**Comment by blueyed** [comment]
Done.

Hmm, I've seen a CI failure, but it appears to be good now?!
https://toxdev.visualstudio.com/tox/_build/results?buildId=1218&view=logs&jobId=5c9cfffa-02af-5931-d194-60c5bf721ca9&taskId=355263bf-342e-5ce0-d70e-7a006ec8e0b4&lineStart=1042&lineEnd=1084&colStart=1&colEnd=77

**Comment by blueyed** [comment]
Ok, now the status shows up as "failed".  For linux_py27.
Any idea?  Works locally.

```
__________________ TestParseconfig.test_workdir_gets_resolved __________________
[gw0] linux2 -- Python 2.7.15 /home/vsts/work/1/s/.tox/py27/bin/python

self = <test_config.TestParseconfig instance at 0x7ff435f96ea8>
tmpdir = local('/home/vsts/work/1/b/pytest-of-vsts/pytest-0/popen-gw0/test_workdir_gets_resolved0')

    @pytest.mark.skipif(sys.platform == "win32", reason="no symlinks on Windows")
    def test_workdir_gets_resolved(self, tmpdir):
        """
        Test explicitly setting config path, both with and without the filename
        """
        real = tmpdir.mkdir("real")
        symlink = tmpdir.join("link")
        symlink.mksymlinkto(real)
    
>       config = parseconfig(["--workdir", str(symlink)])

real       = local('/home/vsts/work/1/b/pytest-of-vsts/pytest-0/popen-gw0/test_workdir_gets_resolved0/real')
self       = <test_config.TestParseconfig instance at 0x7ff435f96ea8>
symlink    = local('/home/vsts/work/1/b/pytest-of-vsts/pytest-0/popen-gw0/test_workdir_gets_resolved0/link')
tmpdir     = local('/home/vsts/work/1/b/pytest-of-vsts/pytest-0/popen-gw0/test_workdir_gets_resolved0')

/home/vsts/work/1/s/tests/unit/config/test_config.py:291: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/tox/config/__init__.py:245: in parseconfig
    feedback(msg.format(candidates), sysexit=not (option.help or option.helpini))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

msg = 'tox config file (either pyproject.toml, tox.ini, setup.cfg) not found'
sysexit = True

    def feedback(msg, sysexit=False):
        print("ERROR: {}".format(msg), file=sys.stderr)
        if sysexit:
>           raise SystemExit(1)
E           SystemExit: 1

msg        = 'tox config file (either pyproject.toml, tox.ini, setup.cfg) not found'
sysexit    = True

/home/vsts/work/1/s/.tox/py27/lib/python2.7/site-packages/tox/config/__init__.py:294: SystemExit
----------------------------- Captured stderr call -----------------------------
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found
=============================== warnings summary ===============================
```

**Comment by blueyed** [comment]
1. Shouldn't it fail on all linux jobs?
2. Shouldn't it find the `tox.ini` from tox itself?  Is this some race where cwd is something else?!

Re-triggered a build, where it also failed for pypy.
Will use `--help` to work around this, but it is not clear to me why it is necessary.

**Comment by gaborbernat** [comment]
Yes probably, we ran tests in parallel, so the cwd is non deterministic (each test should ensure itself the environment is correctly set-up - some bad tests might not reset their changes).

**Comment by blueyed** [comment]
Ok, thanks for the info.

> some bad tests might not reset their changes

Could be ensured maybe with an autouse fixture.

**Comment by gaborbernat** [comment]
Neah to many moving things. Tests should be declarative, and define upfront if they want to really on some stuff (e.g. tox.ini from project). Explicit over implicit.

**Comment by blueyed** [comment]
Well.. tests should also not change the environment, right?  (Why is `monkeypatch.chdir` used in some places then?)

**Comment by blueyed** [comment]
Why is this now?  (only linux_py36)

```
__________________ TestParseconfig.test_workdir_gets_resolved __________________
[gw0] linux -- Python 3.6.5 /home/vsts/work/1/s/.tox/py36/bin/python

self = <test_config.TestParseconfig object at 0x7f06c7614518>
tmpdir = local('/home/vsts/work/1/b/pytest-of-vsts/pytest-0/popen-gw0/test_workdir_gets_resolved0')

    @pytest.mark.skipif(sys.platform == "win32", reason="no symlinks on Windows")
    def test_workdir_gets_resolved(self, tmpdir):
        """
        Test explicitly setting config path, both with and without the filename
        """
        real = tmpdir.mkdir("real")
        symlink = tmpdir.join("link")
        symlink.mksymlinkto(real)
    
        config = parseconfig(["--workdir", str(symlink), "--help"])
>       assert config.toxworkdir == real
E       AttributeError: 'Config' object has no attribute 'toxworkdir'

config     = <tox.config.Config object at 0x7f06c736cf28>
real       = local('/home/vsts/work/1/b/pytest-of-vsts/pytest-0/popen-gw0/test_workdir_gets_resolved0/real')
self       = <test_config.TestParseconfig object at 0x7f06c7614518>
symlink    = local('/home/vsts/work/1/b/pytest-of-vsts/pytest-0/popen-gw0/test_workdir_gets_resolved0/link')
tmpdir     = local('/home/vsts/work/1/b/pytest-of-vsts/pytest-0/popen-gw0/test_workdir_gets_resolved0')

/home/vsts/work/1/s/tests/unit/config/test_config.py:292: AttributeError
----------------------------- Captured stderr call -----------------------------
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found
```

**Comment by gaborbernat** [comment]
we try to clean up after us as much as possible, however much of the tests were written way before this best practice was established☹️ and tox itself changes many states (environment/cwd), so some tests inadvertently miss some of this even if at test level all looks good

**Comment by blueyed** [comment]
Should be good now I guess.
Please squash-merge then.

**Comment by gaborbernat** [comment]
looks good, can you switch to tmp_path please? thanks!

**Comment by gaborbernat** [comment]
we'll also need a changelog entry to warn users about this in case this will cause issues

**Comment by blueyed** [comment]
Thanks for (squash-)merging.
btw: only the first commit's message is really meaningful for the history.

**Pull request merged**
