### PR TITLE
Provide an explanatory message when attempted command parsing produces an empty result

### PR DESCRIPTION
**Pull request by jayaddison**
This attempts to clarify the error messaging when the `install_command` entry in a `tox` environment configuration is empty.

- [ ] ran the linter to address style issues (`tox -e fix`)
- [x] wrote pull request text
- [x] ensured there are test(s) validating the fix
- [x] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation

Continues-from #2715.

Relates to #2695, #2798.

### CODE REVIEW

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Please allow pushes to this PR.

**Comment by jayaddison** [comment]
Maintainer edits should be allowed @gaborbernat (looks like you were able to push some commits, let me know if I can help)

**Comment by gaborbernat** [comment]
```
ERROR: Permission to openculinary/tox.git denied to gaborbernat.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
seems not

**Comment by gaborbernat** [comment]
Why there's like 30 commits here?

**Comment by jayaddison** [comment]
Sometimes (often, recently) I'm a bit tedious about trying to keep the entire commit history for a pull request after it's open (even if it means including reverts, rather than squash committing).

It's kinda about being open about errors and mistakes during development.  But yep, I do worry that it's annoying to read/review, and wonder how to figure out the balance (per-project/community).

I can reduce the commits down if that'd be useful (to a single commit, or to a few logical grouped changes).

**Comment by gaborbernat** [comment]
Replaced with https://github.com/tox-dev/tox/pull/2807

**Comment by gaborbernat** [comment]
Also, please never use merge to make the branch up to date. I always prefer to rebase onto the main, which makes it easier to read and follow.

**Comment by jayaddison** [comment]
Ok, understood :+1:   I'll do my best to remember not to do that again here.

**Pull request closed without merging**
