### PR TITLE
fix isolated builds when stderr is buffered and appears after print()

### PR DESCRIPTION
**Pull request by asottile**
I tried very hard to write a test which reproduces here but unfortunately couldn't -- this is based on the observations from the failing tests in `pytest` on `pypy3`: https://github.com/pytest-dev/pytest/issues/10079

## Contribution checklist:

(also see [CONTRIBUTING.rst](../tree/master/CONTRIBUTING.rst) for details)

- [x] wrote descriptive pull request text
- [x] added/updated test(s) (**couldn't craft a test which reliably failed**)
- [x] updated/extended the documentation **N/A**
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [x] added news fragment in [changelog folder](../tree/master/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`, `breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with ```-- by :user:`<your username>`.```
  * please, use full sentences with correct case and punctuation, for example:
    ```rst
    Fixed an issue with non-ascii contents in doctest text files -- by :user:`superuser`.
    ```
  * also see [examples](../tree/master/docs/changelog)
- [x] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

### CODE REVIEW

**Review by gaborbernat — COMMENTED** [review]
Perhaps a test would be helpful?

**Comment by asottile** [comment]
> Perhaps a test would be helpful?

yeh -- see the first sentence of the PR description.  I tried `atexit`, I tried destructors, I tried unclosed contexts, I tried all sorts of stuff and couldn't get it to reliably reproduce

**Comment by gaborbernat** [comment]
Guess in a few months this will not be used  anyways 😆 

copium

**Comment by gaborbernat** [comment]
https://pypi.org/project/tox/3.25.1/

**Pull request merged**
