### PR TITLE
Unify PyPy into the CI matrix

### PR DESCRIPTION
**Pull request by vtbassmatt**
Hi there, PM for Azure Pipelines here. We recently added `pypy2` and `pypy3` as targets for the `UsePythonVersion` task. This means you no longer have to special-case PyPy and can roll it into your normal matrix.

## Contribution checklist:

(also see [CONTRIBUTING.rst](/CONTRIBUTING.rst) for details)

- [X] wrote descriptive pull request text
- [NA] added/updated test(s)
- [NA] updated/extended the documentation
- [NA] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [NA] added news fragment in [changelog folder](/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`,`breaking`, `doc`, `misc`
  * if pr has no issue: consider creating one first or change it to the pr number after creating the pr
  * "sign" fragment with "by @<your username>"
  * please use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files - by :user:`superuser`."
  * also see [examples](/docs/changelog/examples.rst)
- [NA] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

### CODE REVIEW

**Comment by asottile** [comment]
@vtbassmatt this is awesome!  is there somewhere I can read more about the change

**Comment by vtbassmatt** [comment]
@asottile ha, it looks like it was minor enough that we didn't do release notes for it. I also see that it's not in our [documentation](https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-python-version) which I will fix :)

**Comment by gaborbernat** [comment]
thanks but we're moving to a template, we'll fix it part of that https://github.com/tox-dev/tox/pull/1277/files

**Comment by gaborbernat** [comment]
@vtbassmatt the plan is that all projects using tox will use the template going ahead, so maybe take a look over it if you have time https://github.com/tox-dev/azure-pipelines-template

**Comment by vtbassmatt** [comment]
Can do!

**Comment by vtbassmatt** [comment]
The template looks good to me.

**Pull request closed without merging**
