### PR TITLE
Run tests on macOS. Fixes #446.

### LINKED ISSUE #446: Run tests on OS X with Travis CI?
It's [possible](https://docs.travis-ci.com/user/osx-ci-environment/#Homebrew) and as we officially support it, it might be a good idea.

It would be great, if somebody who works mainly on OS X would step up to do this.

### PR DESCRIPTION
**Pull request by jaraco**

### CODE REVIEW

**Comment by jaraco** [comment]
It took a while to get right due to the 30-70 minute delay between push and test run, but it's now passing. I've noticed other projects have disabled macOS tests in Travis because they're so slow. If you decide not to accept this, I'm okay with it.

**Comment by obestwalter** [comment]
@jaraco thanks a lot. Is this a temporary bottle neck or a permanent problem on Travis CI? I have no experience woth running OS X tests on Travis, so I couldn't say. I'll merge it and if the delay is proving problematic we see what we can do. Let's hope Travis CI buys a few more Macs soon :)

If this turns out to be not working at all, I might adapt @nicoddemus approach: https://github.com/nicoddemus/devpi-cloud-tester - this won't be integrated on Github then though, but at least on devpi.net: https://github.com/nicoddemus/devpi-cloud-tester

**Comment by jaraco** [comment]
> Is this a temporary bottle neck or a permanent problem on Travis CI?

I'm not sure. I've regularly noticed the builds being delayed, but they always seem reliable, if slow. I've enabled them for a few high-profile projects and it's been worthwhile. In my mind, the slowness will only prove problemmatic if some other process is gated on the test acceptance (such as pull requests are). I believe there are some Travis options we could employ to make macOS tests optional.

**Comment by obestwalter** [comment]
Well, [results are in](https://travis-ci.org/tox-dev/tox/jobs/200384153) and everything works fine and I don't really think the slowness will bother us too much then.

Thank you again :)

**Pull request merged**
