### PR TITLE
Verbosity now affects package installation

### PR DESCRIPTION
**Pull request by rogalski**
Solves  #353.

### CODE REVIEW

**Comment by hpk42** [comment]
Thanks for the PR.  See one inline comment.  I wonder if some people will be surprised that ``-vv`` turns of redirection.  If so we might have to rather go for a separate option.  Please amend the help string of ``-v`` to say that if it's supplied twice output from commands will be shown, not redirected to a file.  This way people can discover it via ``tox -h | grep output`` or so.

**Comment by The-Compiler** [comment]
FWIW I'm surprised by the current behaviour - I'd absolutely expect `-vv` to show me pip install output :wink:

**Comment by rogalski** [comment]
After code review is completed, I'll happily squash and rebase change, since right now history is quite messy.

**Comment by hpk42** [comment]
Looks good, thanks!  Please rebase and then we can merge.

**Comment by nicoddemus** [comment]
Went ahead with @hpk42's instructions. 👍

**Pull request merged**
