### PR TITLE
poetry plugin

### LINKED ISSUE #2074: tox plugin documentation is missing poetry
The plugin list for tox documentations is missing the [poetry plugin](https://github.com/tkukushkin/tox-poetry).

### PR DESCRIPTION
**Pull request by chayim**
closes #2074

### CODE REVIEW

**Review by jugmac00 — CHANGES_REQUESTED** [review]
@chayim Thanks for your PR!

Unfortunately, `pip search tox`, which was used to generate the list you want to modify with this PR, currently does not work due to some dos problems.

When you try to run it, you also get a deprecation notice:

```
❯ pip search tox
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.
```

I am not sure whether it makes sense to update this list any more, or maybe create a list with some manual selections?

As I am a happy `tox` user who never used any plugins (oh, except `tox-travis` and `tox-gh-actions`), I would not know which plugins to highlight.

Oh, @gaborbernat created a list of plugins at #1974 - maybe this is a good base?

@chayim Are you ok with rewriting this part of the plugin documentation and advise users to search on PyPI via browser, and list the plugins, suggested by @gaborbernat?

**Comment by chayim** [comment]
I'm happy to do that, I think it's a great answer for now. I'm thinking we list, and link to pypi or Github. Objections?

**Comment by jugmac00** [comment]
> I'm happy to do that, I think it's a great answer for now. I'm thinking we list, and link to pypi or Github. Objections?

Sure, go for it!

I think `PyPI` is better suited.. maybe some projects decide to move to GitLab or whatever at some point in time.

Thank you!

**Comment by chayim** [comment]
> I think `PyPI` is better suited.. maybe some projects decide to move to GitLab or whatever at some point in time.
> 

My pleasure! 

So, it turns out that you can't embed links in a code block. Instead, I've pushed an alphabetized list, based on the linked bug, plus what was here. I've included a link to a PyPI search, which I hope is a happy medium.

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
