### PR TITLE
Add explicit check for pypy venv

### LINKED ISSUE #1355: cowardly pypy bug
I haven't had time to look closer yet, but I am pretty sure that there is a problem with our "do not delete folders that don't look like venvs" protection.

When testing tox-direct it regularly occurs that this is shown:

```text
tox -r -e pypy
GLOB sdist-make: /home/ob/oss/tox-dev/tox-direct/setup.py
pypy recreate: /home/ob/oss/tox-dev/tox-direct/.tox/pypy
ERROR: cowardly refusing to delete `envdir` (it does not look like a virtualenv): /home/ob/oss/tox-dev/tox-direct/.tox/pypy
```

the folder looks fine though:

```text
tree -L 2 .tox/pypy
.tox/pypy
├── bin
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── activate.ps1
│   ├── activate_this.py
│   ├── easy_install
│   ├── easy_install-2.7
│   ├── libpypy-c.so -> /opt/pypy/bin/libpypy-c.so
│   ├── pip
│   ├── pip2
│   ├── pip2.7
│   ├── py.test
│   ├── pypy
│   ├── pytest
│   ├── python -> pypy
│   ├── python-config
│   ├── python2 -> pypy
│   ├── python2.7 -> pypy
│   ├── tox
│   ├── tox-quickstart
│   ├── virtualenv
│   └── wheel
├── include -> /opt/pypy/include
├── lib-python
│   └── 2.7
├── lib_pypy
│   └── readline.py -> /opt/pypy/lib_pypy/readline.py
├── log
│   ├── pypy-0.log
│   ├── pypy-1.log
│   ├── pypy-2.log
│   ├── pypy-3.log
│   ├── pypy-4.log
│   ├── pypy-5.log
│   └── pypy-6.log
├── site-packages
│   ├── _pytest
│   ├── [...]
│   └── zipp.pyc
└── tmp
```

### PR DESCRIPTION
**Pull request by obestwalter**
fixes #1355

### CODE REVIEW

**Comment by obestwalter** [comment]
ooooohh - o.k. changelog entry it is then :)

**Comment by obestwalter** [comment]
@webknjaz is it me or the check? AFAICT it's o.k. now ...

**Comment by webknjaz** [comment]
Oh, the bot assumes `.bugfix` extension and you have `.bugfix.rst`.
I'm curious whether I can automatically get this `.rst` suffix requirement from some config...

*/me looks closer*

**Comment by webknjaz** [comment]
@gaborbernat is this a default behavior of towncrier to also accept `.rst`? Or did you configure anything additionally for this?

**Comment by obestwalter** [comment]
Thanks. Here are the examples for our format: https://github.com/tox-dev/tox/blob/master/docs/changelog/examples.rst

**Comment by webknjaz** [comment]
@obestwalter I know. But I need some way for the bot to figure this out automatically.

Currently, it reads the towncrier config and uses `directory` entries for types to construct a regexp:
https://github.com/sanitizers/chronographer-github-app/blob/51624c6f33f504da38dab7552eaa092465ff8434/chronographer/event_handlers.py#L194-L210

**Comment by obestwalter** [comment]
AFAIK towncrier accepts both (we have also no specific config regarding extensions): https://github.com/tox-dev/tox/blob/master/pyproject.toml#L9

**Comment by obestwalter** [comment]
> But I need some way for the bot to figure this out automatically.

I see :)

**Comment by webknjaz** [comment]
Yeah, I just try to avoid hardcoding things. Maybe I'll add a per-repo `postfix` option via `.github/config.yaml` to control this...

**Comment by webknjaz** [comment]
*/me goes to the towncrier repo to read the actual code...*

**Comment by webknjaz** [comment]
Interesting... They can also be numbered: https://github.com/hawkowl/towncrier/blob/master/src/towncrier/_builder.py#L58

**Comment by obestwalter** [comment]
Wouldn't really know what to use this for, but good to know it exists :)

**Comment by webknjaz** [comment]
@obestwalter AFAIU it's for the case if you want several fragments attached to the issue. You could submit:
```console
docs/changelog/1355.bugfix.rst
docs/changelog/1355.bugfix.1.rst
docs/changelog/1355.feature.0.rst
docs/changelog/1355.feature.1.rst
```

**Comment by asottile** [comment]
(this was the failure before the patch):

```
    def assert_success(self, is_run_test_env=True):
        msg = self.output()
>       assert self.ret == 0, msg
E       AssertionError: 2
E       
E       GLOB sdist-make: /tmp/pytest-of-asottile/pytest-3/popen-gw0/test_recreate0/example/setup.py
E       py recreate: /tmp/pytest-of-asottile/pytest-3/popen-gw0/test_recreate0/example/.tox/py
E       ERROR: cowardly refusing to delete `envdir` (it does not look like a virtualenv): /tmp/pytest-of-asottile/pytest-3/popen-gw0/test_recreate0/example/.tox/py
E       ___________________________________ summary ____________________________________
E       ERROR:   py: error
```

**Comment by obestwalter** [comment]
Great - thanks :)

**Comment by obestwalter** [comment]
I'd also like to merge it and make a bugfix release soon. It's almost a year ago that I made the last release, so time to get back into the game :man_playing_water_polo: 

The "new" release process looks pretty straightforward but I'll need a secret key I don't have yet. Could you sent it to me via https://keybase.io/obestwalter ? Thanks!

**Comment by webknjaz** [comment]
Wow! Did you switch to signing dists with GPG?

**Comment by asottile** [comment]
@gaborbernat was saying that part is optional so I skipped it when I released :laughing:

**Comment by webknjaz** [comment]
Is it documented somewhere? I was thinking of exploring this but wasn't sure. I want to see what can be automated there...

**Comment by asottile** [comment]
We don't sign our dists, the key is for sending an email: https://github.com/tox-dev/tox/blob/master/HOWTORELEASE.rst

**Comment by webknjaz** [comment]
Still nice :)

**Comment by webknjaz** [comment]
Meanwhile, I promptly patched chronographer https://github.com/sanitizers/chronographer-github-app/commit/070cf3840a64008339e5acfabfd29e59a8e1ee4e

**Pull request merged**
