### PR TITLE
Explicitly specify AppVeyor image to VS 2017

### PR DESCRIPTION
**Pull request by gaborbernat**
:+1:

### CODE REVIEW

**Comment by gaborbernat** [comment]
It's a test to see build time difference compared to VS 2015.

**Comment by nicoddemus** [comment]
I'm curious, what was the conclusion here?

**Comment by gaborbernat** [comment]
Still a work in progress :thinking:

**Comment by nicoddemus** [comment]
Weird, I wouldn't expect any change actually. Oh well. 😁

**Pull request merged**
