### PR TITLE
Remove py25-specific code

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
I initially wanted to do this with [pre-commit](http://pre-commit.com) and [reorder-python-imports](https://github.com/asottile/reorder_python_imports) via this config:

```yaml
repos:
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
        args: [
            '--remove-import', 'from __future__ import with_statement',
        ]
```

but this introduced a lot of diff and I wasn't sure if you had preferences for import order (and wasn't sure if you wanted to adopt the framework either) -- here's the diff it would produce: https://i.fluffy.cc/7T4vhl1klMN5Gm56f9r3CScV3j46TJ70.html

**Comment by asottile** [comment]
@nicoddemus any thoughts on the other patch in the comment above?  one big plus of having a tool sort imports is it reduces merge conflicts in imports significantly

**Comment by nicoddemus** [comment]
Yeah I'm all yup for having a known import-order-policy, specially if it is enforced by a tool. 👍 

Btw thanks @asottile for all your work on tox recently, we all certainly appreciate it!

**Comment by asottile** [comment]
Cool, I'll cook up a PR for it :)

**Pull request merged**
