### PR TITLE
fix skip with package = wheel

### PR DESCRIPTION
**Pull request by MarcinKonowalczyk**
Fix for #3153

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [x] ensured there are test(s) validating the fix
- [x] added news fragment in `docs/changelog` folder
- [n/a] updated/extended the documentation

### CODE REVIEW

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Test please

**Comment by MarcinKonowalczyk** [comment]
Ok, the only failing test is `test_depends.py` due to missing output lines: 
Screenshot 2024-04-26 at 18 28 13

Any hint as to where am I supposed to return that status? (sorry, a bit lost in the code) so far i'm looking at `report` called from `execute`, both in common.py

**Comment by MarcinKonowalczyk** [comment]
For reference, here is the stack from the failing case:
```
Traceback (most recent call last):
  File ".../tox/src/tox/run.py", line 20, in run
    result = main(sys.argv[1:] if args is None else args)
  File ".../tox/src/tox/run.py", line 46, in main
    return handler(state)
  File ".../tox/src/tox/session/cmd/legacy.py", line 115, in legacy
    return run_sequential(state)
  File ".../tox/src/tox/session/cmd/run/sequential.py", line 25, in run_sequential
    return execute(state, max_workers=1, has_spinner=False, live=True)
  File ".../tox/src/tox/session/cmd/run/common.py", line 170, in execute
    cast(RunToxEnv, state.envs[name]).mark_active()
  File ".../tox/src/tox/tox_env/runner.py", line 211, in mark_active
    for pkg_env in self.package_envs:
  File ".../tox/src/tox/tox_env/runner.py", line 208, in package_envs
    yield from self.package_env.child_pkg_envs(self.conf)
  File ".../tox/src/tox/tox_env/python/package.py", line 124, in child_pkg_envs
    conf = run_conf["wheel_build_env"]
  File ".../tox/src/tox/config/sets.py", line 116, in __getitem__
    return self.load(item)
  File ".../tox/src/tox/config/sets.py", line 127, in load
    return config_definition.__call__(self._conf, self.loaders, ConfigLoadArgs(chain, self.name, self.env_name))  # noqa: PLC2801
  File ".../tox/src/tox/config/of_type.py", line 111, in __call__
    value = self.default(conf, args.env_name) if callable(self.default) else self.default
  File ".../tox/src/tox/tox_env/python/package.py", line 93, in default_wheel_tag
    run_py = cast(Python, run_env).base_python
  File ".../tox/src/tox/tox_env/python/api.py", line 260, in base_python
    raise Skip(msg)
tox.tox_env.errors.Skip: could not find python interpreter with spec(s): py310
```

**Comment by MarcinKonowalczyk** [comment]
ok, compared and matched the behaviour to `package = sdist`. After stepping through the code it looks like it was nothing to do with the report, which looks correct when running the normal `tox` command with the patch on a test repo.

**Comment by MarcinKonowalczyk** [comment]
also patched `_make_tox_wheel` to allow `pytest --run-integration` run with a dev patch version

**Review by gaborbernat — APPROVED** [review]

**Comment by gaborbernat** [comment]
Thank you for your contribution.

**Pull request merged**
