### PR TITLE
document environments for projects tox.ini

### PR DESCRIPTION
**Pull request by gaborbernat**
- also now all config values can be substituted (so e.g. basepython can be used inside the description)
- ignore IDEA project files

### CODE REVIEW

**Comment by gaborbernat** [comment]
@obestwalter @The-Compiler any reasons why we don't run the unit tests with the project itself? (and instead install a dependency that runs it, basically guarantying that we run the tests with an older version of tox?)

**Comment by obestwalter** [comment]
@gaborbernat no, no idea, but just a hunch: make sure that tox is always tested with a stable version of tox.

**Comment by gaborbernat** [comment]
so how should we handle this then? 

A. bump the tests to use the latest
B. keep testing with an older version:  remove substitution of basepython for now, and derail it until we release a new tox version

**Comment by nicoddemus** [comment]
IMHO it makes sense to have at least one job in Travis and AppVeyor where the tests are run "in-place" instead of using `tox` itself.

**Comment by obestwalter** [comment]
Any idea, why all tests fail with

    ERROR: tox version is 2.7, required is at least 2.7.1.dev13

?

**Comment by The-Compiler** [comment]
Because the PR added `minversion=2.7.1.dev13` - see the comments above yours.

**Comment by obestwalter** [comment]
It shouldn't then.

**Comment by gaborbernat** [comment]
@obestwalter but it needs that to pass because the tox.ini uses a feature added in this version/PR. hence my earlier question here:

[@obestwalter](https://github.com/obestwalter) [@The-Compiler](https://github.com/the-compiler) any reasons why we don't run the unit tests with the project itself? (and instead install a dependency that runs it, basically guarantying that we run the tests with an older version of tox?)

**Comment by obestwalter** [comment]
Hi @gaborbernat - sorry, I was a bit too dense yesterday. What I meant, was that we just can't do it this way at the moment. We have to add the change that make substitutions possible now and release that and then add the docs. So for now the descriptions in the tox.ini can't contain substitutions on from 2.8+ they can. That would be my preferred path to sneak that in.

So if you update the PR that way (please have a look at my other comments) with 2.8+ the use of substitutions will be possible.

We can definitely discuss the way how we test tox and how we can improve it, but I think this should happen in a separate issue or on the tox-dev mailing list (or IRL next week at EuroPython :)). There usually are downsides to any such change and they need to be considered first and also communicated to the other contributors. So this would be something that we can tackle after 2.8 is out of the way.

**Comment by obestwalter** [comment]
Adding missing issue ref: https://github.com/tox-dev/tox/issues/499

**Comment by obestwalter** [comment]
Sorry: s/then add the docs/add the substitutions in tox.ini/

**Comment by gaborbernat** [comment]
Hello, I'll amend it tomorrow 👍 sadly my company is not supporting me yet to attend EuroPython. But yes we can discuss how this is handled. 

In a more general I would like to tackle the project review/ownership how it works. This PR has stayed in limbo for a month until you got some time on your hand, and I do understand it's summer and people have lot on their hand. As I stated earlier I would like to contribute but with this rate of response  even simple changes such as this takes a significant amount of time that discourages me to do so.

**Comment by obestwalter** [comment]
Hi @gaborbernat, I understand that it is sometimes frustrating that things take longer in OSS projects but that's just how it is: there is always significantly more work than people who are willing and able to do it. And the work involves so much more than writing the code. Just for comparison: my own PR about starting to use setuptools_scm was open for more than a month and it is still not released. I don't consider that particularly slow, it's just how it is. If you look at other projects there are tons of unanswered issues and PRs that are open for more than a year, so I really think we're doing alright here.

It is also a question of priorities. One "problem" that tox has, is that a lot of projects rely on it in their build chain, so my philisophy since I somehow took over release management was to provide stable releases that don't introduce new bugs, rather than quick releases that might break thousands of CI builds. 

As I still have no intimate knowledge of the code base yet, I might be rather on the conservative side as it is hard for me to evaluate the impact of certain changes. So, I for one am also a bit frustrated at the moment, because I almost entirely served as a project manager/release manager/pr reviewer/issue triager since I joined the project and if this is the only thing you do (as a developer), this gets old quite quickly. Therefore I would also really like to tackle some issues in the code myself and do less of the other stuff, but I want to put that on a better footing by improving the way we organize the project first. I started writing things down this weekend and will open the discussion about that soon. I also opened issues about code coverage and release candidates to help speed up releases.

If you want to join the project and also help with issue traiging, reviews and testing, let us know. I would be thrilled to have more active people in the project, as the "old" maintainers are very busy with their other projects, so tox was a bit on the back burner for quite a while, I guess. One caveat though: you would still have to open PRs for non trivial changes and you still might have to wait just like now. 

Talking prioritization: in the present phase of the project it would be important to fix known bugs (see https://github.com/tox-dev/tox/projects/1), improve existing behaviour (e.g. https://github.com/tox-dev/tox/projects/3) and have a good look at the internal structure and do some refactoring to keep the code base maintainable. This is what I want to concentrate on in the next months, so I might even get more conservative when it's about introducing new features, unless many people ask for them. On the other hand: I really like the introduction of descriptions that you initiated and I use them in my own projects, so thanks a lot for that :)

**Comment by gaborbernat** [comment]
@obestwalter thanks for the detailed outline, sounds like a good plan!

PS. As for the change sorry for being late, but my laptop died on me, and it will be a few more days until I get a replacement.

**Comment by obestwalter** [comment]
Wow - thats bad. Hope nothing important got lost. Take your time - patience goes both ways :)

**Comment by gaborbernat** [comment]
@obestwalter done now :+1:

**Comment by obestwalter** [comment]
Thanks @gaborbernat  :)

**Pull request merged**
