### PR TITLE
Touch up tests

### PR DESCRIPTION
**Pull request by jurko-gospodnetic**
Touched up some test code while researching where to add tests for some other work in progress.

- removed commented out debugging code
- removed commented out checks that already has a valid alternative
- replaced commented out checks with valid alternatives where missing
- extended `test_config_parse_platform_with_factors()` with a missing check

- added `test_envconfigs_based_on_factors()` showing how requested environment names are interpreted based on which environment name factors we have defined in the tox configuration

### CODE REVIEW

**Comment by The-Compiler** [comment]
Why not merge it before? It's not like it makes anything worse for the stuff already failing :wink:

**Comment by asottile** [comment]
Makes the little green badge turn red, shrugs it's probably fine to merge :P

**Comment by jurko-gospodnetic** [comment]
mergy mergy? :-) so we can start on reviewing the issue #292 pull request (currently a temporary pull request is up for review at jurko-gospodnetic#1)

**Comment by gaborbernat** [comment]
@jurko-gospodnetic fixup the conflict, and let's see how the CI reacts

**Comment by jurko-gospodnetic** [comment]
@gaborbernat - fix branch rebased on top of the current `master`

**Pull request merged**
