### PR TITLE
log env-var changes with double verbosity and into log files

### LINKED ISSUE #1361: log environment variable changes
To debug some failures it's important to understand how the environment changes alongside calls. Add a way to log these at two plus verbosity level.

### PR DESCRIPTION
**Pull request by gaborbernat**
Resolves #1361.

### CODE REVIEW

**Comment by obestwalter** [comment]
There is a lot going on here that on first sight has not much to do with the title of the PR. Can you explain this a bit more?

**Comment by webknjaz** [comment]
Also needs rebasing...

**Comment by gaborbernat** [comment]
Everything else not related to the tile is just noise because of the lack of rebase. Needs tests though, hence why this is waiting here patiently. The free time I've had in the last month has been focused on rewriting virtualenv which in turn would essentially make so that we can delete the entire interpreters package. WIP

**Comment by webknjaz** [comment]
@gaborbernat you may want to integrate https://github.com/apps/wip

**Comment by gaborbernat** [comment]
Withdrawn 👍

**Comment by MaineSoNewOrleans504** [comment]
Help 
Idk he to use github

**Pull request closed without merging**
