### PR TITLE
release 3.1.3

### PR DESCRIPTION
**Pull request by gaborbernat**
first with vsts :+1:

### CODE REVIEW

**Comment by gaborbernat** [comment]
There's a slight duplication here. Seems both the tag and the pr ci runs even though they are the same. Moreover, the tag commit is not added as ci check. Plus needed some fixing on the vsts side to trigger build on tags.

**Comment by gaborbernat** [comment]
The release should happen on https://toxdev.visualstudio.com/tox/_build/results?buildId=250&view=logs.

**Comment by gaborbernat** [comment]
Success.

**Comment by nicoddemus** [comment]
Congrats on the first with VSTS! I'm curious, is there a badge for VSTS?

**Pull request closed without merging**
