### PR TITLE
Clean up dead code

### PR DESCRIPTION
**Pull request by asottile**
Using https://github.com/asottile/dead

### CODE REVIEW

**Comment by asottile** [comment]
not sure what's up with CI so I ran it locally:

```
$ tox -e py36
py36 inst-nodeps: /home/asottile/workspace/tox/.tox/.tmp/package/1/tox-3.6.2.dev13+g7f322f3.tar.gz
py36 installed: apipkg==1.5,atomicwrites==1.2.1,attrs==18.2.0,coverage==4.5.2,distro==1.3.0,execnet==1.5.0,filelock==3.0.10,more-itertools==5.0.0,pluggy==0.8.0,py==1.7.0,pytest==3.10.1,pytest-cov==2.6.1,pytest-forked==0.2,pytest-mock==1.10.0,pytest-randomly==1.2.3,pytest-timeout==1.3.3,pytest-xdist==1.25.0,six==1.12.0,toml==0.10.0,tox==3.6.2.dev13+g7f322f3,virtualenv==16.2.0
py36 run-test-pre: PYTHONHASHSEED='1127762368'
py36 runtests: commands[0] | pytest --cov=/home/asottile/workspace/tox/.tox/py36/lib/python3.6/site-packages/tox --cov-config=/home/asottile/workspace/tox/tox.ini --timeout=180 -n=auto --junitxml=/home/asottile/workspace/tox/.tox/.test.py36.xml .
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
Using --randomly-seed=1546965989
tox comes from: '/home/asottile/workspace/tox/.tox/py36/lib/python3.6/site-packages/tox/__init__.py'
rootdir: /home/asottile/workspace/tox, inifile: tox.ini
plugins: xdist-1.25.0, timeout-1.3.3, randomly-1.2.3, mock-1.10.0, forked-0.2, cov-2.6.1
timeout: 180.0s
timeout method: signal
timeout func_only: False
gw0 [468] / gw1 ok / gw2 [468] / gw3 ok / gw4 [468] / gw5 ok / gw6 ok / gw7 [468gw0 [468] / gw1 ok / gw2 [468] / gw3 [468] / gw4 [468] / gw5 ok / gw6 ok / gw7 [gw0 [468] / gw1 ok / gw2 [468] / gw3 [468] / gw4 [468] / gw5 [468] / gw6 ok / gwgw0 [468] / gw1 ok / gw2 [468] / gw3 [468] / gw4 [468] / gw5 [468] / gw6 [468] /gw0 [468] / gw1 [468] / gw2 [468] / gw3 [468] / gw4 [468] / gw5 [468] / gw6 [468] / gw7 [468]
.................s...................................................... [ 15%]
........................................................................ [ 30%]
.....................................................................s.. [ 46%]
........................................................................ [ 61%]
........................................................................ [ 76%]
........................................................................ [ 92%]
....................................                                     [100%]
----- generated xml file: /home/asottile/workspace/tox/.tox/.test.py36.xml -----

----------- coverage: platform linux, python 3.6.7-final-0 -----------
Name                                                                    Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------------------------------------
.tox/py36/lib/python3.6/site-packages/tox/__main__.py                       1      1      0      0     0%   1
.tox/py36/lib/python3.6/site-packages/tox/_pytestplugin.py                277    222     70      2    16%   27, 29, 47-48, 53-63, 68-95, 100-106, 109-111, 114-115, 119, 122, 129-132, 135, 138-147, 150-159, 166-182, 190, 195-201, 205, 208, 213-236, 241-245, 249-252, 281-344, 348-358, 365, 378-389, 393-398, 408-495, 502, 26->27, 28->29
.tox/py36/lib/python3.6/site-packages/tox/_quickstart.py                  122    122     57      0     0%   2-279
.tox/py36/lib/python3.6/site-packages/tox/cli.py                            7      7      0      0     0%   1-11
.tox/py36/lib/python3.6/site-packages/tox/config.py                       885    744    337      0    12%   40-55, 62-63, 69, 86, 94-98, 101, 104, 109-113, 123-146, 155-160, 165-171, 181-193, 203-207, 218-238, 242-244, 248-266, 270-278, 282-284, 288-295, 302-305, 308, 311, 314-328, 331-334, 337, 340-341, 346-796, 804-811, 826-835, 839-842, 854-861, 870-873, 877, 882, 886-890, 897-898, 903, 906-917, 924-927, 931-934, 939-1064, 1067-1072, 1078-1087, 1094-1099, 1102-1132, 1135-1165, 1170-1174, 1178, 1182, 1186-1193, 1197-1198, 1203-1211, 1215, 1220-1221, 1224-1228, 1235-1236, 1248-1257, 1260-1262, 1265-1267, 1270-1273, 1276-1279, 1282-1283, 1286-1289, 1292-1301, 1304-1319, 1322-1323, 1326, 1329-1349, 1352-1354, 1357-1370, 1373-1388, 1404-1405, 1412-1421, 1424-1460, 1463-1472, 1475-1489, 1492-1498, 1502, 1517-1541, 1545-1578, 1584-1586, 1589, 1592-1643, 1647-1649
.tox/py36/lib/python3.6/site-packages/tox/exception.py                     37     18      8      0    42%   17-31, 36, 44, 63-65, 68, 87-88
.tox/py36/lib/python3.6/site-packages/tox/interpreters.py                 120     96     32      1    16%   14-16, 24-29, 32-41, 44-59, 63-76, 80-92, 97-100, 105-109, 112, 117-121, 124-127, 134-179, 130->141
.tox/py36/lib/python3.6/site-packages/tox/package/__init__.py              50     50     10      0     0%   1-68
.tox/py36/lib/python3.6/site-packages/tox/package/builder/__init__.py       6      6      2      0     0%   1-9
.tox/py36/lib/python3.6/site-packages/tox/package/builder/isolated.py      64     64     25      0     0%   1-135
.tox/py36/lib/python3.6/site-packages/tox/package/builder/legacy.py        26     26      8      0     0%   1-46
.tox/py36/lib/python3.6/site-packages/tox/package/view.py                  26     26     10      0     0%   1-45
.tox/py36/lib/python3.6/site-packages/tox/result.py                        47     29      4      0    35%   11-19, 25, 32-34, 37, 42-44, 47-57, 60, 63, 68-69, 72-77
.tox/py36/lib/python3.6/site-packages/tox/session.py                      540    456    196      0    11%   29-36, 40-42, 46-58, 62, 66-76, 80-90, 95-112, 115-116, 119, 122-126, 129, 132-144, 156-253, 256-266, 269-271, 292-294, 298-303, 307-310, 313-316, 319-324, 327-328, 331-333, 336-337, 340, 343-347, 350, 353, 356, 359, 362, 365, 368, 371, 374, 377, 384-400, 403-412, 416, 419-430, 434-437, 440-442, 445-455, 459-471, 474-477, 480-526, 529-531, 534-540, 550-557, 560-586, 593-597, 600-608, 611-644, 647-659, 662-686, 689-695, 698-702, 705-730, 737-745
.tox/py36/lib/python3.6/site-packages/tox/util.py                          10      7      2      0    25%   8-16
.tox/py36/lib/python3.6/site-packages/tox/venv.py                         379    324    150      0    10%   28-34, 37-48, 52-74, 77-98, 101-102, 107-108, 112, 117, 121, 126, 129, 138-154, 157-162, 165, 168, 171-172, 183-191, 197-223, 226-236, 247-254, 257, 260, 263-267, 272-311, 314-332, 335, 338, 341-346, 349-374, 377-392, 395-417, 420-435, 446-498, 513-525, 531-534, 549-558, 563-576, 581-586, 591-592, 597-600, 612, 624-629
src/tox/__main__.py                                                         1      1      0      0     0%   1
src/tox/_pytestplugin.py                                                  277     66     70      5    78%   1-45, 51, 66, 69, 88, 98-99, 108, 113, 117, 121-128, 134-137, 139, 149, 165, 189, 193-194, 203, 207, 211, 239, 248-255, 347, 361, 368, 392, 401, 498, 68->69, 87->88, 138->139, 169->182, 396->393
src/tox/_quickstart.py                                                    122     19     57      7    83%   76, 83, 91, 99, 116-128, 132-134, 275-277, 75->76, 82->83, 90->91, 98->99, 114->116, 176->186, 178->177
src/tox/cli.py                                                              7      7      0      0     0%   1-11
src/tox/config.py                                                         885     15    337     18    97%   333, 808, 871, 958, 1012, 1119, 1123, 1226, 1445-1446, 1457, 1465, 1522, 1536, 1571, 184->192, 332->333, 560->572, 807->808, 840->842, 870->871, 954->958, 1011->1012, 1071->exit, 1118->1119, 1120->1123, 1225->1226, 1456->1457, 1464->1465, 1479->1489, 1521->1522, 1535->1536, 1552->1571
src/tox/interpreters.py                                                   120     36     32      3    62%   55-57, 73-74, 85, 87, 90-91, 141-179, 84->85, 86->87, 130->141
src/tox/package/__init__.py                                                50      4     10      2    90%   21-22, 55-56, 20->21, 51->59
src/tox/package/builder/isolated.py                                        64      3     25      2    94%   36-40, 24->27, 35->36
src/tox/package/view.py                                                    26      3     10      2    86%   34-35, 37, 30->36, 36->37
src/tox/result.py                                                          47      1      4      1    96%   14, 13->14
src/tox/session.py                                                        540     20    196     13    95%   54, 200, 220, 229-231, 263-265, 340, 498-500, 505, 538-540, 626-627, 725, 739, 53->54, 198->200, 219->220, 235->exit, 244->246, 251->253, 262->263, 327->exit, 497->498, 504->505, 625->626, 724->725, 738->739
src/tox/venv.py                                                           379     14    150     11    95%   95, 129, 149, 185-186, 219, 396, 468-472, 497-498, 522, 94->95, 143->146, 146->149, 184->185, 188->187, 189->188, 265->exit, 395->396, 467->468, 494->458, 521->522
-------------------------------------------------------------------------------------------------------------------
TOTAL                                                                    5292   2387   1846     67    52%

12 files skipped due to complete coverage.

=========================== short test summary info ============================
SKIP [1] tests/integration/test_jython_env_create.py:5: needs jython and dev cut of virtualenv
SKIP [1] tests/unit/test_interpreters.py:28: non posix test
==================== 466 passed, 2 skipped in 70.27 seconds ====================
___________________________________ summary ____________________________________
  py36: commands succeeded
  congratulations :)
```

**Comment by gaborbernat** [comment]
CI should be fixed after https://github.com/tox-dev/tox/pull/1126

**Comment by gaborbernat** [comment]
Eh I would have prefered to merge after CI passes :-D

**Comment by asottile** [comment]
oh, oops!  I ran the suite locally so I'm pretty sure it works :man_shrugging:

**Comment by gaborbernat** [comment]
the master passed now yay we're good

**Pull request merged**
