### PR TITLE
Display durations with verbosity 1 already

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/tox-dev/tox/issues/1450.

### CODE REVIEW

**Comment by gaborbernat** [comment]
I'd rather keep it at level 2. If anything let's move pip verbose one level deeper.

**Comment by blueyed** [comment]
Well, it was based on https://github.com/tox-dev/tox/issues/1450#issuecomment-552219848.

> If anything let's move pip verbose one level deeper

Might make sense in general, but there's no `verbosity3` yet at least.
It would also break the expected outcome for people using `-vv` and suddenly missing it.

> Also, such behaviour changes should be accompanied by tests to defend against regressions.

:+1:

I will go with a custom tox version I think, given that an explicit `--durations` flag to enable this always was also rejected already.

**Comment by gaborbernat** [comment]
Still not sure why you don't want to do this via a plugin 🤔

**Comment by blueyed** [comment]
> just bump the level of the print from above to use the verbosity1 instead of verbosity2.

Not sure what you mean - I've looked into creating a plugin that just monkeypatches `timed_operation` to use `verbosity1`, but that's likely not what you mean / is recommended.

Apart from that I'd rather use a fork with that simple patch, where I can also add TERM and CI to passenv by default.. :)

**Comment by gaborbernat** [comment]
As I said before for both of those features I have some reservations. If you can convince another maintainer (@asottile or @obestwalter) that we should do this I'll accept; otherwise, I'll recommend to do it via a plugin.

**Comment by asottile** [comment]
plug-in seems the best approach here :+1:

**Comment by blueyed** [comment]
@gaborbernat
I've said already that I'm fine with a fork.

I would still be interested to know what you've meant with "just bump the level of the print from above to use the verbosity1 instead of verbosity2" in the context of a plugin though.

For reference: https://github.com/tox-dev/tox-durations

**Comment by obestwalter** [comment]
> As I said before for both of those features I have some reservations. If you can convince another maintainer (@asottile or @obestwalter) that we should do this I'll accept

I just want to mention that I am more a hibernating maintainer and a lot of the finer things elude me as I haven't been able to follow discussions and development for quite a while ... again *sigh* :(

To give my opinion more from a user perspective, I would prefer completely decoupling durations from verbosity and instead have a  `--durations` flag as proposed in #1450 I simply had not seen this, otherwise I'd already would have said so.
Best explanation I can come up with why I feel that way:

1. IMO It's hard to decide what is the "correct" verbosity level to show durations - I'd say it's impossible to find the right level, because the right level doesn't exist. durations are just a different kind of information that I better explicitly aks for rather than having them pop up from a certain level onwards (and yes: this viewpoint is also a matter of taste :)). The more I teach people in the use of tox, the more I am aware of the shortcomings of our output in general and I really hope I can help improve that, so I'd like to start with us thinking about disentangling the kind of information we burden the user with in any given tox run. Durations would be an easy win to unclutter the output (even if it is verbose) by saying: "durations" is something you can have, if you explicitly ask for it.

2. Thinking across project borders: pytest has `--durations` and why should we do it differently from our sister project? Learn how to get durations in one project and you know how to get them in the other ...

**Pull request closed without merging**
