### PR TITLE
Fix SetuptoolsDeprecationWarning about using --global-option

### LINKED ISSUE #2478: Warning about `"--global-option": ["--formats=gztar"]` emitted when using setuptools 64.0.1
When using tox to build or install a setuptools-based package, if the tox-created virtualenv contains setuptools v64.0.1, then the following warning is emitted:

```
/Users/jwodder/work/pyproj/linesep/.tox/.package/lib/python3.9/site-packages/setuptools/build_meta.py:306: SetuptoolsDeprecationWarning:
            The arguments ['--formats=gztar'] were given via `--global-option`.
            Please use `--build-option` instead,
            `--global-option` is reserved to flags like `--verbose` or `--quiet`.
```

This appears to be due to [this line of code](https://github.com/tox-dev/tox/blob/d98f589197f033fa9846918f309bf66a645f905b/src/tox/helper/build_isolated.py#L41) in tox's source.

# To Reproduce

1. Clone, say, https://github.com/jwodder/linesep
2. Ensure virtualenv uses the latest version of setuptools by running `virtualenv --upgrade-embed-wheels`
3. Run `tox`

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #2478.

## Contribution checklist:

(also see [CONTRIBUTING.rst](../tree/master/CONTRIBUTING.rst) for details)

- [x] wrote descriptive pull request text
- [x] added/updated test(s)
- [x] updated/extended the documentation
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [x] added news fragment in [changelog folder](../tree/master/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`, `breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with ```-- by :user:`<your username>`.```
  * please, use full sentences with correct case and punctuation, for example:
    ```rst
    Fixed an issue with non-ascii contents in doctest text files -- by :user:`superuser`.
    ```
  * also see [examples](../tree/master/docs/changelog)
- [x] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

### CODE REVIEW

**Comment by asottile** [comment]
what versions of setuptools does the new argument require ?

**Review by gaborbernat — APPROVED** [review]

**Comment by adamchainz** [comment]
I tested down to setuptools 50 and got no error.

But looking at the setuptools code, it seems `--build-option` was actually introduced in setuptools 63: https://github.com/pypa/setuptools/pull/3380 . So perhaps when I used older versions, it was just being ignored.

**Comment by asottile** [comment]
@gaborbernat I don't think this could go out as is given the above

**Comment by gaborbernat** [comment]
I guess the question here if older setuptools just ignored this flag or actually used it 🤔

**Comment by asottile** [comment]
I believe on windows the flag is important -- otherwise it'll default to zip ?

**Comment by gaborbernat** [comment]
Would that cause a problem for pip?

**Comment by asottile** [comment]
it shouldn't be a problem for pip -- but I thought tox tries to read the tgz -- maybe I'm misremembering how this works -- not at a computer to check

**Comment by gaborbernat** [comment]
tox does not read the file 🤔

**Comment by asottile** [comment]
this is what I was thinking of but looks like it already supports zip: https://github.com/tox-dev/tox/blob/d98f589197f033fa9846918f309bf66a645f905b/src/tox/package/local.py#L52

we can probably drop the option entirely then

**Comment by adamchainz** [comment]
That seems reasonable to me too, done in #2497.

**Pull request merged**
