### PR TITLE
use IOError and check error number (py2/py3 compat)

### PR DESCRIPTION
**Pull request by obestwalter**
FileNotFoundError was introduced in Python3, so this is not compatible with python2.

### CODE REVIEW

**Comment by obestwalter** [comment]
I'd like to merge this and make it part of an rc2 soon. Anyone opposed?

**Comment by nicoddemus** [comment]
Sounds good to me! 👍

**Comment by gaborbernat** [comment]
agreed 👍

**Comment by obestwalter** [comment]
thanks :)

**Pull request merged**
