### PR TITLE
release 3.9.0

### PR DESCRIPTION
**Pull request by gaborbernat**

### CODE REVIEW

**Comment by gaborbernat** [comment]
Publish here once CI passes f you want to follow it https://dev.azure.com/toxdev/tox/_build/results?buildId=1547

**Comment by webknjaz** [comment]
@gaborbernat it seems like `test_parallel_recreate` failed under Windows.

**Comment by webknjaz** [comment]
But tox v3.9.0 has been published successfully: https://pypi.org/project/tox/3.9.0

**Comment by gaborbernat** [comment]
That's a flaky test 😢

**Pull request merged**
