### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by webknjaz**
## Thanks for contributing a pull request!

If you are contributing for the first time or provide a trivial fix don't worry too
much about the checklist - we will help you get started.

## Contribution checklist:

(also see [CONTRIBUTING.rst](/CONTRIBUTING.rst) for details)

- [ ] wrote descriptive pull request text
- [ ] added/updated test(s)
- [ ] updated/extended the documentation
- [ ] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [ ] added news fragment in [changelog folder](/docs/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`,`breaking`, `doc`, `misc`
  * if PR has no issue: consider creating one first or change it to the PR number after creating the PR
  * "sign" fragment with "by :user:`<your username>`"
  * please use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files - by :user:`superuser`."
  * also see [examples](/docs/changelog/examples.rst)
- [ ] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

### CODE REVIEW

**Comment by webknjaz** [comment]
@asottile @gaborbernat plz don't interact with this PR. It's for debugging :) I've already caught one traceback...

**Comment by webknjaz** [comment]
Alright, it works. Feel free to do your own tests just in case.

**Comment by gaborbernat** [comment]
Seems good to me 👍 I'll close it as such for now 👍

**Comment by gaborbernat** [comment]
@webknjaz thanks a lot for this!

**Comment by webknjaz** [comment]
Perfect! I may be creating extra test PRs should I need to test more improvements later.

**Pull request closed without merging**
