### PR TITLE
Hint for possible signal upon InvocationError

### PR DESCRIPTION
**Pull request by ederag**
This is a follow up to issue #760, with changes outlined in https://github.com/tox-dev/tox/pull/760#issuecomment-364700302.
An indication for the potential signal received is given, with the method suggested by @asottile in https://github.com/tox-dev/tox/pull/760#discussion_r165831005.

Tests have been reworked with a new dependency: [`pytest-mock`](https://pypi.python.org/pypi/pytest-mock). This mainly allowed to
- remove 1 out of 3 slow tests in `test_z_cmdline.py`.
- keep code coverage with negligible increase in testing time, while adding tests for different platforms.
indeed, the signal hint is given only on `posix` systems.
`monkeypatch` has been used to fake system: windows ([`os.name == 'nt'`](https://docs.python.org/3/library/os.html#os.uname)) or `posix` ([`os.name == 'posix'`](https://docs.python.org/3/library/os.html#os.uname))

Should this PR be accepted, please merge squashing all commits into a single one, with message
`hint for possible signal upon InvocationError + better tests`.

- [x] wrote descriptive pull request text
- [x] added/updated test(s)
- [x] updated/extended the documentation
- [ ] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/) in message body
- [x] added news fragment in [changelog folder](https://github.com/tox-dev/tox/tree/master/changelog)

### CODE REVIEW

**Comment by ederag** [comment]
The `appveyor` tests failed with
```
>           assert expected_command_arg in call_command
E           assert 'python -c import sys; sys.exit(6)' in "'c:\\\\users\\\\appveyor\\\\appdata\\\\local\\\\temp\\\\1\\\\pytest-0\\\\test_exit_code_6_0\\\\foo\\\\.tox\\\\foo\\\\Scripts\\\\python.EXE -c import sys; sys.exit(6)'"
```
The command `python` given in tox.ini has been changed to `python.EXE`.
Is there a way to get the actual command ? `result = cmd()` does not contain this.
Meanwhile, just removing "python" from `expected_command_arg`.

**Comment by ederag** [comment]
@gaborbernat thanks for merging.
But I would have left some time for @asottile to review this request too. @asottile, if you find some improvements, please comment here, and I'll be ready to file another PR.

And the commit message could have been clearer:
> Should this PR be accepted, please merge squashing all commits into a single one, with message
> hint for possible signal upon InvocationError + better tests.

Or was it not possible with github ?

**Comment by gaborbernat** [comment]
It's a squash merge on master 👍

**Comment by ederag** [comment]
@gaborbernat Isn't it possible on github to do the equivalent of
`git merge --squash -m "hint for possible signal upon InvocationError + better tests"` ?

**Pull request merged**
