### PR TITLE
Add favicon and logo to sphinx docs

### PR DESCRIPTION
**Pull request by hazalozturk**
Here are the proposed changes:
1) Changing the sphinx theme to **alabaster** (to be consistent with [pytest](https://docs.pytest.org/en/latest/))
2) Adding logo as discussed [here](https://github.com/tox-dev/tox/issues/639)
3) Creating a favicon with the chosen logo

tox-sphinx-alabaster

## Contribution checklist:

(also see [CONTRIBUTING.rst](https://github.com/tox-dev/tox/tree/master/CONTRIBUTING.rst) for details)

- [x] wrote descriptive pull request text
- [ ] added/updated test(s)
- [x] updated/extended the documentation
- [x] added relevant [issue keyword](https://help.github.com/articles/closing-issues-using-keywords/)
      in message body
- [ ] added news fragment in [changelog folder](https://github.com/tox-dev/tox/tree/master/changelog)
  * fragment name: `<issue number>.<type>.rst` for example (588.bugfix.rst)
  * `<type>` is must be one of `bugfix`, `feature`, `deprecation`,`breaking`, `doc`, `misc`
  * if pr has no issue: consider creating one first or change it to the pr number after creating the pr
  * "sign" fragment with "by @<your username>"
  * please use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files - by @superuser."
  * also see [examples](https://github.com/tox-dev/tox/tree/master/changelog/examples.rst)
- [x] added yourself to `CONTRIBUTORS` (preserving alphabetical order)

### CODE REVIEW

**Comment by gaborbernat** [comment]
@hazalozturk thanks for this, can you add thew news fragment? thanks!

**Comment by The-Compiler** [comment]
Aren't favicons still displayed in 16x16 in many pages? This definitely isn't noticable at all when resizing it to 16x16.

**Comment by gaborbernat** [comment]
on my notebook, it's decent the favicon size :+1: I can read it

**Comment by gaborbernat** [comment]
Thanks for the contribution @hazalozturk  👍

**Comment by hazalozturk** [comment]
You are very welcome @gaborbernat !
Please let me know if you need another design's svg (I think there is still some debate about the arrow of this design).

**Pull request merged**
